- name: Create an ec2 instance
  ec2:
    key_name: "{{ keypair }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    group: SGI  # security group name
    instance_type: "{{ instance_type}}"
    image: "{{ ami }}"
    wait: true
    region: "{{ region }}"
    count: 1  # default
    count_tag:
      Name: "Demo"
    instance_tags:
      Name: "Demo"
    vpc_subnet_id: "subnet-e11491ad"
    assign_public_ip: yes
  register: ec2
    
- debug:
    msg: "{{ item['private_ip'] }}"
  with_items: "{{ ec2.instances }}"

- name: Add all web instance IPs to host group
  add_host: 
    hostname: "{{ item.private_ip }}"
    groupname: webservers
    ansible_user: ubuntu 
  with_items: '{{ ec2.instances }}'

- name: Wait for SSH to come up
  wait_for: host={{ item.public_dns_name }} port=22 delay=180 timeout=500 state=started
  with_items: '{{ ec2.instances }}'
