---
# tasks file for install-app
- name: Update APT package manager repositories cache
  become: true
  apt:
    update_cache: yes

- name: Install dependencies
  apt: update_cache=yes
  apt: name='{{ item }}' state=present
  with_items:
   - python3
   - python3-pip
   - python3-setuptools
   - python3-dev
   - build-essential
   - python3-mysqldb
  tags:
    - packages

- name: Upgrade pip
  pip: name=pip state=latest
  tags:
    - packages

- name: Install MySQL database
  apt:
    name: '{{ item }}'
    state:  present
  with_items:
   - mysql-server
   - mysql-client

- name: Start Mysql Service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Create Application Database
  mysql_db: name={{ db_name }} state=present

- name: Create Application DB User
  mysql_user: name={{ db_user }} password={{ db_password }} priv='*.*:ALL' host='%' state='present'

- name: Install Python Flask dependencies
  pip:
    name: "{{ item }}"
    state: present
  with_items:
   - flask
   - flask-mysql

- name: Copy web-server code
  copy: src=app.py dest=/opt/app.py

- name: Start web-application
  shell: FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &
